// Type definitions for Node.js 10.12
// Project: http://nodejs.org/
/** Declaration file generated by dts-gen */

export class inputStream {
	constructor();

	init(...args: any[]): any;
	push(data: any): void;
	on(ev: string, fn: (data: any) => void): void;
}

export class outputStream {
	constructor();

	init(...args: any[]): any;
	push(data: any): void;
	on(ev: string, fn: (data: any) => void): void;
}

export class packStream {
	constructor();

	init(...args: any[]): any;
	push(data: any): void;
	on(ev: string, fn: (data: any) => void): void;
}

export class unpackStream {
	constructor();

	init(...args: any[]): any;
	push(data: any): void;
	on(ev: string, fn: (data: any) => void): void;
}
